FROM python:3.12-slim

WORKDIR /app

COPY api_gateway/requirements.txt .
RUN pip install --no-cache-dir --trusted-host pypi.org --trusted-host files.pythonhosted.org -r requirements.txt

COPY api_gateway/ ./api_gateway/

CMD ["uvicorn", "api_gateway.app:app", "--host", "0.0.0.0", "--port", "8080"]
